version: '3.8'
services:
  firebase:
    build:
      context: .
      dockerfile: Dockerfile
      target: firebase
    ports:
      - 9091:9091 # Firebase Authentication
      - 8081:8081 # Cloud Firestore
      - 4001:4001 # Emulator Suite UI
