version: '3.8'
services:
  domore:
    build:
      context: .
      dockerfile: Dockerfile
      target: domore
    ports:
      - "8000:8000"
  firebase:
    build:
      context: .
      dockerfile: Dockerfile
      target: firebase
    ports:
      - "8080:8080"
      - "9099:9099"
      - "5000:5000"
